### PR TITLE
included bullet points for info

### PR DESCRIPTION
**Pull request by michaeljokf**
we want to add more information to the data page
hopefully this is a list of bullet points on the variables
plus a paragraph of text before it - a link with an additional PDF still needs to be added

### CODE REVIEW

**Comment by DianaMPG** [comment]
@kravets-levko just to be clear - these change requests refer to the specification? 
If yes, @michaeljokf and @annafralberts please review

**Comment by annafralberts** [comment]
We are adding with several pull requests:
- The information for the data tab
- New Information to the methodology
- New text for the footer

These are simple changes of the modal files.

**Comment by kravets-levko** [comment]
@annafralberts (cc @DianaMPG) Thank you for clarification. So, please review each PR and approve it - it will be a signal to me that everything is ok and can be merged. Thanks!

**Comment by annafralberts** [comment]
@akariv It is my pull request, so would you mind reviewing it :) Especially for html, bullet point list and if it is not horrible ugly as it comes out etc.

**Review by akariv — APPROVED** [review]

**Pull request merged**
