### PR TITLE
updated links and changed headers

### PR DESCRIPTION
**Pull request by michaeljokf**
I added the new links for the documents that offer the documentation for the website. Basically I changed the three links above
and changed the names of the headers.

### CODE REVIEW

**Comment by DianaMPG** [comment]
@kravets-levko does this refer to the Data/Resources/Github?

**Comment by michaeljokf** [comment]
Hey Diana this is Michael ;) yes it does. It is information that we are
adding - plus the nicely formatted pdfs instead of the Google doc links!

Am 03.02.2017 7:48 vorm. schrieb "DianaMPG" <notifications@github.com>:

**Comment by DianaMPG** [comment]
@michaeljokf good morning :-)
thank you for the clarification, Michael.

**Comment by kravets-levko** [comment]
Hi @DianaMPG! I need your review because I don't know who requested this changes, and therefore cannot decide should it be merged or not. So if you approve this changes - I can merge this PR.

**Comment by annafralberts** [comment]
@akariv Hellow! Can you also review and approve this one? Thanks !

**Review by akariv — APPROVED** [review]

**Pull request merged**
