### PR TITLE
moving the disclaimer

### PR DESCRIPTION
**Pull request by michaeljokf**
trying to move the disclaimer text "Please note..." below the drop down bar. 
Not 100% sure that this works, therefore creating a branch and requesting a PR.

### CODE REVIEW

**Comment by kravets-levko** [comment]
@michaeljokf I'll check it

**Comment by kravets-levko** [comment]
So, disclaimer is below dropdown (as you expected):
image

But there should be less space, WDYT?

**Comment by michaeljokf** [comment]
Thank you @kravets-levko yes agreed - should be less space! 
BTW other issue I included a dataset description for Austria - if you have time to run it, I would like to see what it looks like before including all the others. Preparing them offline atm and will upload the rest of the descriptions today.

**Comment by kravets-levko** [comment]
@michaeljokf Okay, I'll fix that spacing within openspending/subsidystories.eu/issues/31

**Pull request merged**
