### PR TITLE
changes to text and hyperlinks

### PR DESCRIPTION
**Pull request by michaeljokf**
changed some text and hyperlinks that had to be amended, nothing major.

### CODE REVIEW

**Comment by kravets-levko** [comment]
@michaeljokf  Hope you know what you do :blush: Merging.

**Comment by michaeljokf** [comment]
@kravets-levko I thought I did ;) somehow none of the changes I made went through to the website. Maybe the website hasnt been updated after the PR was merged? I just changed some of the text and some hyperlinks - so nothing to complicated.

**Comment by kravets-levko** [comment]
@michaeljokf Try it now

**Comment by michaeljokf** [comment]
@kravets-levko yes thank you very much! I will probably have to make some last text changes one more time here in the next week. I will let you know ;)

**Comment by kravets-levko** [comment]
okay @michaeljokf, no problem :+1:

**Pull request merged**
